# -*- coding: utf-8 -*-
"""langgraph_03.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18qAs8rb1kOqXr_9G1e5d5NS6zHKO6YWC
"""

!pip install langchain==0.3.24 -q
!pip install langchain-openai -q
!pip install langchain-community -q
!pip install langgraph -q

!pip install langchain-tavily -q
!pip install pyowm -qU

from typing import Annotated, Sequence, TypedDict
from langchain_core.messages import BaseMessage, ToolMessage, SystemMessage
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langgraph.graph.message import add_messages
from langgraph.graph import StateGraph, START, END
from langgraph.prebuilt import ToolNode

class AgentState(TypedDict):
    messages: Annotated[Sequence[BaseMessage], add_messages]

import os
from google.colab import userdata

os.environ['OPENAI_API_KEY'] = ""

llm = ChatOpenAI(model = "gpt-4o")

from langchain_tavily import TavilySearch
from langchain_community.utilities import OpenWeatherMapAPIWrapper
from langchain_classic.agents import load_tools

os.environ["OPENWEATHERMAP_API_KEY"] = "4c0113d32192a14b56b2cbe7e2c88ea1"
os.environ['TAVILY_API_KEY'] = "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"

# Initialize google search tool
search_tool = TavilySearch()

# Initialize OpenWeatherMap tool
weather = OpenWeatherMapAPIWrapper()

weather_tool = load_tools(["openweathermap-api"], llm)[0]

# tools = [addtion, subtraction, multiplication, division]
tools = [search_tool, weather_tool]

llm_with_tools = llm.bind_tools(tools)

def llm_call(state:AgentState) -> AgentState:
    system_prompt = SystemMessage(content=
        "You are an intelligent AI assistant."
    )
    response = llm_with_tools.invoke([system_prompt] + state["messages"])
    return {"messages": [response]}


def decision(state: AgentState):
    messages = state["messages"]
    last_message = messages[-1]
    if not last_message.tool_calls:
        return "end"
    else:
        return "continue"

graph = StateGraph(AgentState)

graph.add_node("agent", llm_call)
tool_node = ToolNode(tools=tools)
graph.add_node("tools", tool_node)

graph.set_entry_point("agent")
graph.add_conditional_edges(
    "agent",
    decision,
    {
        "continue": "tools",
        "end": END,
    },
)
graph.add_edge("tools", "agent")

app = graph.compile()

from IPython.display import Image, display
display(Image(app.get_graph().draw_mermaid_png()))

def print_stream(stream):
    for s in stream:
        message = s["messages"][-1]
        if isinstance(message, tuple):
            print(message)
        else:
            message.pretty_print()

inputs = {"messages": [("user", "What is the current temperature in Colombo?")]}
print_stream(app.stream(inputs, stream_mode="values"))

inputs = {"messages": [("user", "president in srilanka")]}
print_stream(app.stream(inputs, stream_mode="values"))

